/*
    Master UI Resource File
*/
#include "common.hpp"



#include "admin_menu.hpp"
#include "bank.hpp"
#include "car_processing.hpp"
#include "cell_phone.hpp"
#include "chop_shop.hpp"
#include "clothing.hpp"
#include "compensate.hpp"
#include "craft.hpp"
#include "crew.hpp"
#include "deathScreen.hpp"
#include "federalReserve.hpp"
#include "FuelStat.hpp"
#include "gang.hpp"
#include "impound.hpp"
#include "impoundvehicles.hpp"
#include "jail_time.hpp"
#include "kaution.hpp"
#include "key_chain.hpp"
#include "market.hpp"
#include "newsStation.hpp"
#include "pInteraction.hpp"
#include "player_inv.hpp"
#include "prof.hpp"
#include "settings.hpp"
#include "shop_items.hpp"
#include "shops.hpp"
#include "smartphone.hpp"
#include "spawnSelection.hpp"
#include "ticket.hpp"
#include "trunk.hpp"
#include "schliessfach.hpp"
#include "ui.hpp"
#include "vehicleShop.hpp"
#include "vehicleShop3D.hpp"
#include "vehicleShopMarket.hpp"
#include "wanted_list.hpp"
#include "wantedadd2.hpp"
#include "civ_ausweis.hpp"
#include "cop_ausweis.hpp"
#include "adac_ausweis.hpp"
#include "ems_ausweis.hpp"
